### ISSUE TITLE
[feat] 차량 인식 및 개수 파악

### ISSUE THREAD

**Issue by happy-yeachan** [Smart-Parking-PJ/Image-Processing#8]
## ✨ 필요 기능 요약

정확도가 높은 실시간 주차 현환을 제공하기 위해서 가장 중요한 이슈
차량을 인식하고 대수를 파악하는 최적의 코드가 필요함

## ✅체크리스트
- [ ] 차량 인식률이 70% 이상인가?
- [ ] 차량의 대수가 카운트가 가능한가?

**Comment by Yu-Jaeyoung** [comment]
Interactive Rebase는 위와 같이 유용하게 활용될 수 있습니다!
같이 공부해봅시다 :)

**Comment by happy-yeachan** [comment]
Haaracascade를 이용한 처리보다 Yolo를 이용한 처리가 정확도가 월등히 높음
하지만 속도적인 측면은 Haaracascade가 압도적이다.

**Comment by happy-yeachan** [comment]
너무 주기적인 반복으로 인해 차량 개수의 차이가 발생  
-> 오차 발생 조치가 필요할듯
